language: ruby
rvm:
  - 2.2.6
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

services:
  - mongodb

before_install:
  - gem install bundler -v '~> 1.13'

bundler_args: --jobs=2 --without development staging production

before_script:
  - cp config/secrets.travis.yml config/secrets.yml

script: "bundle exec rake spec"

cache: bundler
