---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: HabitEC API JSON Schema
description: In this schema file, we represents the public interface of HabitEC API in JSON Hyper Schema draft v4.
id: habitec-api
links:
  - href: https://example.com
    rel: self
