---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Sample API JSON Schema
description: In this schema file, we represents the public interface of Sample API in JSON Hyper Schema draft v4.
id: sample
links:
  - href: https://example.com
    rel: self
